service: spy-search
frameworkVersion: '2'
provider:
  name: azure
  region: East US
  runtime: python3.7
  os: linux
  environment:
    VARIABLE_FOO: foo
plugins:
  - serverless-azure-functions
package:
  exclude:
    - env/**
    - .env/**
    - local.settings.json
    - .vscode/**
    - __pycache__/**
    - node_modules/**
    - .python_packages/**
    - .funcignore
    - package.json
    - package-lock.json
    - .gitignore
    - .git/**
functions:
  seeq-search:
    handler: src/handlers/SpyPull.main
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
    name: spy-search-dev